## install and addons part taken from googletest project

# Blacklist
branches:
  except:
    - gh-pages

install:
# /usr/bin/gcc is 4.6 always, but gcc-X.Y is available.
- if [ "$CXX" = "g++" ]; then export CXX="g++-4.9" CC="gcc-4.9"; fi
# /usr/bin/clang is 3.4, lets override with modern one.
- if [ "$CXX" = "clang++" ] && [ "$TRAVIS_OS_NAME" = "linux" ]; then export CXX="clang++-3.7" CC="clang-3.7"; fi
- echo ${PATH}
- echo ${CXX}
- ${CXX} --version
- ${CXX} -v
addons:
  apt:
    # List of whitelisted in travis packages for ubuntu-precise can be found here:
    #   https://github.com/travis-ci/apt-package-whitelist/blob/master/ubuntu-precise
    # List of whitelisted in travis apt-sources:
    #   https://github.com/travis-ci/apt-source-whitelist/blob/master/ubuntu.json
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.7
    packages:
    - gcc-4.9
    - g++-4.9
    - clang-3.7
    - valgrind
    - doxygen
    - doxygen-doc
    - doxygen-latex
    - doxygen-gui
    - graphviz

language: cpp
compiler:
- clang
- gcc
os:
- linux
- osx
script: bash ./.travis_build_and_test.sh

# Generate and deploy documentation
after_success:
- bash -x ./.travis_create_doxygen_and_deploy.sh
env:
  global:
    secure: uvq3Y6ZOXAMlAAC1lQIHAT1V+6DscskyZZw/nEd5lSdtldDRV3gWK0lrMLL4G3DQKy3tB0onoFravnew8u8KYYnnfvQ7YSyAmeo4j9oeZaUaeqpR0v2+EYCydL5hnLoQmLcoqPwhv6jAwXSehmQCh0/B4KvruL/jlxUiwn+GcYUwumjIJad3U+zM6TPUHuN9jCIqlX12X86PuuBOn+1uFbpte91bAenuHkkKvlkjAl5dt2QZUwgZt8zjvWPCcQaYvAOioFoPUpDSc2p2i3pS6jelWk8ih2QtqEUedYd65Edsp2rN8aLQgd7qEQRE+3MdqFUKkW0O2btUL26HiliNFPckPCPmUApNvHwvSu1biLIISWyU2Qj2Ee2kAnN8MUVLaYPJkhzZcfGx/PDGyCboXVu7fKsvUJE6VUmQJF/wsizS0BAK8k8sn70QEO2NVZkrBBlvIpt/YIAUKtrIXjX1wnXI6kr/Tpz9xsZDdgrhjivG5Hu3hwQqCDG6ooGg8AmBFxRK9u6FH+gEbJW4Z87qNj3l109UkLoybRmxe78TFcRzFi3Zz6Nq6HYjqO/nAVDjVrVM5950u6W+UQQGdP6ofBqiMrV1zLdpET3wa5rhDoeSQsqFV9xWOonWy13pDgrMmRV27ubdDmw65trUH+F5dKGhJ99bYnGfBhx1LprpVNY=
