## install and addons part taken from googletest project

# Blacklist
branches:
  except:
    - gh-pages

install:
# /usr/bin/gcc is 4.6 always, but gcc-X.Y is available.
- if [ "$CXX" = "g++" ]; then export CXX="g++-4.9" CC="gcc-4.9"; fi
# /usr/bin/clang is 3.4, lets override with modern one.
- if [ "$CXX" = "clang++" ] && [ "$TRAVIS_OS_NAME" = "linux" ]; then export CXX="clang++-3.7" CC="clang-3.7"; fi
- echo ${PATH}
- echo ${CXX}
- ${CXX} --version
- ${CXX} -v
addons:
  apt:
    # List of whitelisted in travis packages for ubuntu-precise can be found here:
    #   https://github.com/travis-ci/apt-package-whitelist/blob/master/ubuntu-precise
    # List of whitelisted in travis apt-sources:
    #   https://github.com/travis-ci/apt-source-whitelist/blob/master/ubuntu.json
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.7
    packages:
    - gcc-4.9
    - g++-4.9
    - clang-3.7
    - valgrind
    - doxygen
    - doxygen-doc
    - doxygen-latex
    - doxygen-gui
    - graphviz

language: cpp
compiler:
- clang
- gcc
os:
- linux
- osx
script: bash ./.travis_build_and_test.sh

# Generate and deploy documentation
after_success:
  - bash -x ./.travis_create_doxygen_and_deploy.sh

env:
  global:
    secure: Voxj9sGtmzCsUJ4BoYq5KmsVuiwK/ebSRhav++tbWsJgYyJBE6rfDcpp6Ijd/xWVA/NxBHvS9JfpLLPNRo4qlqK0faMcfC2reMmUUwQBYyZLjLrz72VGUQNoGL8XqdPR7JiyP1N0XlN/ogwWokdDhx4fYTF+jLeqNg1mubKJD91QDAT5oCxCa6+Aukv02AK3+nz1drGmbJiOrLdZZrXoDL1fyLDCeGfiw7d4IVm7qlei8H2zr104xOKMxOAM1bUM47o25pjD2SgXLbwH/PUOCn1xSulO8CCe/iKUXXEfyHMwQbx39BKqfO0yZhcOGkgGc3XDYC6o6iH+KilP+EU1jM0/H+ra87hcyWbE+Q7Llt6uGhv91wsYrZUOWD8ZmEqyRh9YWGlTeqEbxFnzquURyaoAsVICn/U6TgiTqItgmC4DQlU+QmCaxcPu4/X+E3CJJLXcHvA6d/xJpLNqnOpNOkbFST+vVpT5nWTTbX/46coid38mDIEClfh2QKSZntR4eGCzOuo56/2mt9udI4GZabliYbPp881mB3nTEjlkr0+qDIBC2DTRJWrp9kydUlquYee3IU7gCuVx4fy9nUIJVZ1Ak1t5xD7ZdutzyU2hQ6ZmiN7cZmpbNTCg1ePSCiu/VhiBTiMTexYpm9F24AiVGwRZmvO5PPccvxs14VsmkLo=
