DesignByContract++: DesignByContractPlusPlus::InvariantChecker Class Reference
DesignByContractPlusPlus::InvariantChecker Class Reference
#include <dbcpp.h>
Classes
struct staticFunctionHelper
Public Member Functions
InvariantChecker (char const *const file, const int line, const std::function< bool()> &invF)
~InvariantChecker ()
The destructor executes the provided checks.
Protected Member Functions
std::string failPositionText () const
Create text for identifying position in source file.
Static Protected Member Functions
static void assertContract (const bool cond, const std::string msg, const std::string traceText)
The general function that checks if a condition holds.
Private Member Functions
std::string invariantFailText () const
Create fail text for invariant.
std::string invariantTraceText () const
Create fail text for invariant.
Private Attributes
char const *const m_file
The file where the check is declared.
const std::function< bool()> m_invF
The invariant to be checked.
const int m_line
The line of the file where the check is declared.
Static Private Attributes
static staticFunctionHelper< bool > s_staticFunctionHelper
Friends
void setFailFunction (std::function< void(const std::string &)> fn)
void setTraceFunction (std::function< void(const std::string &)> fn)
Detailed Description
Definition at line 40 of file dbcpp.h.
Constructor & Destructor Documentation
DesignByContractPlusPlus::InvariantChecker::InvariantChecker (char const *const file, const int line, const std::function< bool()> & invF) [inline]
Create a checker object that runs the checks when it leaves is context (function)
Parameters:
file File where the check is declared (created by preprocessor __FILE__ directive)
line Line in file where the check is declared (created by preprocessor __LINE__ directive)
invF The invariant to check (implicitely `invariant()`)
Definition at line 50 of file dbcpp.h.
References assertContract(), invariantFailText(), invariantTraceText(), and m_invF.
        : m_file(file),
          m_line(line),
          m_invF(invF)
        {
          assertContract(m_invF(), invariantFailText(), invariantTraceText());
        }
DesignByContractPlusPlus::InvariantChecker::~InvariantChecker () [inline]
The destructor executes the provided checks.
Definition at line 59 of file dbcpp.h.
References assertContract(), invariantFailText(), invariantTraceText(), and m_invF.
{
          assertContract(m_invF(), invariantFailText(), invariantTraceText());
      }
Member Function Documentation
static void DesignByContractPlusPlus::InvariantChecker::assertContract (const bool cond, const std::string msg, const std::string traceText) [inline, static, protected]
The general function that checks if a condition holds.
Definition at line 72 of file dbcpp.h.
References DesignByContractPlusPlus::InvariantChecker::staticFunctionHelper< T >::s_failFunction, s_staticFunctionHelper, and DesignByContractPlusPlus::InvariantChecker::staticFunctionHelper< T >::s_traceFunction.
Referenced by InvariantChecker(), DesignByContractPlusPlus::PreConditionChecker::PreConditionChecker(), ~InvariantChecker(), and DesignByContractPlusPlus::PostConditionChecker::~PostConditionChecker().
{
      s_staticFunctionHelper.s_traceFunction(traceText);
      if (!(cond)) {
        s_staticFunctionHelper.s_failFunction(msg);
      }
    }
std::string DesignByContractPlusPlus::InvariantChecker::failPositionText () const [inline, protected]
Create text for identifying position in source file.
Definition at line 65 of file dbcpp.h.
References m_file, and m_line.
Referenced by DesignByContractPlusPlus::PostConditionChecker::postconditionFailText(), DesignByContractPlusPlus::PostConditionChecker::postconditionTraceText(), DesignByContractPlusPlus::PreConditionChecker::preconditionFailText(), and DesignByContractPlusPlus::PreConditionChecker::preconditionTraceText().
{
      std::ostringstream out;
      out << m_file << ":" << m_line;
      return out.str();
    }
std::string DesignByContractPlusPlus::InvariantChecker::invariantFailText () const [inline, private]
Create fail text for invariant.
Definition at line 81 of file dbcpp.h.
References m_file, and m_line.
Referenced by InvariantChecker(), and ~InvariantChecker().
{
      std::ostringstream out;
      out << "Invariant check failed. Required at: " << m_file << ":" << m_line << "\n";
      return out.str();
    }
std::string DesignByContractPlusPlus::InvariantChecker::invariantTraceText () const [inline, private]
Create fail text for invariant.
Definition at line 88 of file dbcpp.h.
References m_file, and m_line.
Referenced by InvariantChecker(), and ~InvariantChecker().
{
      std::ostringstream out;
      out << "Checking Invariant. Required at: " << m_file << ":" << m_line << "\n";
      return out.str();
    }
Friends And Related Function Documentation
void setFailFunction (std::function< void(const std::string &)> fn) [friend]
void setTraceFunction (std::function< void(const std::string &)> fn) [friend]
Member Data Documentation
char const* const DesignByContractPlusPlus::InvariantChecker::m_file [private]
The file where the check is declared.
Definition at line 96 of file dbcpp.h.
Referenced by failPositionText(), invariantFailText(), and invariantTraceText().
const std::function<bool ()> DesignByContractPlusPlus::InvariantChecker::m_invF [private]
The invariant to be checked.
Definition at line 100 of file dbcpp.h.
Referenced by InvariantChecker(), and ~InvariantChecker().
const int DesignByContractPlusPlus::InvariantChecker::m_line [private]
The line of the file where the check is declared.
Definition at line 98 of file dbcpp.h.
Referenced by failPositionText(), invariantFailText(), and invariantTraceText().
staticFunctionHelper<bool> DesignByContractPlusPlus::InvariantChecker::s_staticFunctionHelper [static, private]
Definition at line 109 of file dbcpp.h.
Referenced by assertContract(), DesignByContractPlusPlus::setFailFunction(), and DesignByContractPlusPlus::setTraceFunction().
The documentation for this class was generated from the following file:
dbcpp.h