DesignByContract++: DesignByContractPlusPlus::PreConditionChecker Class Reference
DesignByContractPlusPlus::PreConditionChecker Class Reference
#include <dbcpp.h>
Public Member Functions
PreConditionChecker (char const *const condExpr, char const *const file, const int line, const std::function< bool()> &preF, const std::function< bool()> &invF)
Protected Member Functions
std::string failPositionText () const
Create text for identifying position in source file.
Static Protected Member Functions
static void assertContract (const bool cond, const std::string msg, const std::string traceText)
The general function that checks if a condition holds.
Private Member Functions
std::string preconditionFailText () const
Create fail text for precondition.
std::string preconditionTraceText () const
Private Attributes
char const *const m_condExpr
The postcondition as a string.
const std::function< bool()> m_preF
The postcondition to check.
Detailed Description
Helper class that allow postcondition and invariant checks at the end of a function This works by postponing the conditions to be checked when the destructor of the class is called.
Definition at line 135 of file dbcpp.h.
Constructor & Destructor Documentation
DesignByContractPlusPlus::PreConditionChecker::PreConditionChecker (char const *const condExpr, char const *const file, const int line, const std::function< bool()> & preF, const std::function< bool()> & invF) [inline]
Create a checker object that runs the checks when it leaves is context (function)
Parameters:
condExpr String of the expression (created by preprocessor stringize operator '#')
file File where the check is declared (created by preprocessor __FILE__ directive)
line Line in file where the check is declared (created by preprocessor __LINE__ directive)
postF The postcondition to check (lambda)
invF The invariant to check (implicitely `invariant()`)
Definition at line 145 of file dbcpp.h.
References DesignByContractPlusPlus::InvariantChecker::assertContract(), m_preF, preconditionFailText(), and preconditionTraceText().
        : InvariantChecker(file, line, invF),
          m_condExpr(condExpr),
          m_preF(preF)
        {
          assertContract(m_preF(), preconditionFailText(), preconditionTraceText());
        }
Member Function Documentation
static void DesignByContractPlusPlus::InvariantChecker::assertContract (const bool cond, const std::string msg, const std::string traceText) [inline, static, protected, inherited]
The general function that checks if a condition holds.
Definition at line 72 of file dbcpp.h.
References DesignByContractPlusPlus::InvariantChecker::staticFunctionHelper< T >::s_failFunction, DesignByContractPlusPlus::InvariantChecker::s_staticFunctionHelper, and DesignByContractPlusPlus::InvariantChecker::staticFunctionHelper< T >::s_traceFunction.
Referenced by DesignByContractPlusPlus::InvariantChecker::InvariantChecker(), PreConditionChecker(), DesignByContractPlusPlus::InvariantChecker::~InvariantChecker(), and DesignByContractPlusPlus::PostConditionChecker::~PostConditionChecker().
{
      s_staticFunctionHelper.s_traceFunction(traceText);
      if (!(cond)) {
        s_staticFunctionHelper.s_failFunction(msg);
      }
    }
std::string DesignByContractPlusPlus::InvariantChecker::failPositionText () const [inline, protected, inherited]
Create text for identifying position in source file.
Definition at line 65 of file dbcpp.h.
References DesignByContractPlusPlus::InvariantChecker::m_file, and DesignByContractPlusPlus::InvariantChecker::m_line.
Referenced by DesignByContractPlusPlus::PostConditionChecker::postconditionFailText(), DesignByContractPlusPlus::PostConditionChecker::postconditionTraceText(), preconditionFailText(), and preconditionTraceText().
{
      std::ostringstream out;
      out << m_file << ":" << m_line;
      return out.str();
    }
std::string DesignByContractPlusPlus::PreConditionChecker::preconditionFailText () const [inline, private]
Create fail text for precondition.
Definition at line 155 of file dbcpp.h.
References DesignByContractPlusPlus::InvariantChecker::failPositionText(), and m_condExpr.
Referenced by PreConditionChecker().
{
        std::ostringstream out;
        out << "Precondition failed (" << m_condExpr << ") in " << failPositionText() << "\n";
        return out.str();
      }
std::string DesignByContractPlusPlus::PreConditionChecker::preconditionTraceText () const [inline, private]
Definition at line 161 of file dbcpp.h.
References DesignByContractPlusPlus::InvariantChecker::failPositionText(), and m_condExpr.
Referenced by PreConditionChecker().
{
        std::ostringstream out;
        out << "Checking Precondition (" << m_condExpr << ") in " << failPositionText() << "\n";
        return out.str();
      }
Member Data Documentation
char const* const DesignByContractPlusPlus::PreConditionChecker::m_condExpr [private]
The postcondition as a string.
Definition at line 169 of file dbcpp.h.
Referenced by preconditionFailText(), and preconditionTraceText().
const std::function<bool ()> DesignByContractPlusPlus::PreConditionChecker::m_preF [private]
The postcondition to check.
Definition at line 171 of file dbcpp.h.
Referenced by PreConditionChecker().
The documentation for this class was generated from the following file:
dbcpp.h