DesignByContract++: DesignByContractPlusPlus::InvariantChecker::staticFunctionHelper< T > Struct Template Reference
DesignByContractPlusPlus::InvariantChecker::staticFunctionHelper< T > Struct Template Reference
Static Public Attributes
static std::function< void(const
std::string &)> s_failFunction
static std::function< void(const
std::string &)> s_traceFunction = [](const std::string&){}
Detailed Description
template<typename T>
struct DesignByContractPlusPlus::InvariantChecker::staticFunctionHelper< T >
Definition at line 104 of file dbcpp.h.
Member Data Documentation
template<typename T> std::function< void(const std::string &)> DesignByContractPlusPlus::InvariantChecker::staticFunctionHelper< T >::s_failFunction [static]
Initial value:
 [](const std::string& msg){
      std::cerr << msg;
      abort();}
The general error function that is called if a contract fails
Todo:
this function can be customized
Definition at line 106 of file dbcpp.h.
Referenced by DesignByContractPlusPlus::InvariantChecker::assertContract(), and DesignByContractPlusPlus::setFailFunction().
template<typename T> std::function< void(const std::string &)> DesignByContractPlusPlus::InvariantChecker::staticFunctionHelper< T >::s_traceFunction = [](const std::string&){} [static]
Definition at line 107 of file dbcpp.h.
Referenced by DesignByContractPlusPlus::InvariantChecker::assertContract(), and DesignByContractPlusPlus::setTraceFunction().
The documentation for this struct was generated from the following file:
dbcpp.h